### ISSUE TITLE
No syntax highlight on any type of files. All text is plain white\black

### ISSUE THREAD

**Issue by wmw9** [gitpod-io/openvscode-server#103]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Deploy docker image
2. Open 0.0.0.0:3000

Rust, Go, YAML, JSON, any syntax highlight does not work. All text is plain white or black.
![Screenshot 2021-09-30 003408](https://user-images.githubusercontent.com/4693125/135352373-89ce03af-8b77-46b3-8dca-a1d612b9bd6c.jpg)

**Comment by wmw9** [comment]
Fixed! Works on another PC, gotta clear cookies then.

**Comment by borgdylan** [comment]
@wmw9 How did you fix it?

**Comment by wmw9** [comment]
@borgdylan sorry, I'm not quite sure, was long time ago. It was just probably about clearing browser cookies or smth lk th

**Comment by borgdylan** [comment]
The solution is to turn off the security mode in Edge using an entry in the whitelist.
