### ISSUE TITLE
Log shows `http://localhost:3000` while actually being available on 0.0.0.0

### ISSUE THREAD

**Issue by afq984** [gitpod-io/openvscode-server#107]
https://github.com/gitpod-io/openvscode-server/blob/aa211ec893de214588c6955d15d325aa03bae60d/src/vs/server/node/server.main.ts#L1020

When the server is listening on 0.0.0.0, the log shows:

```
[main 2021-09-29T23:06:42.971Z] Web UI available at http://localhost:3000
```

which may give a false impression of openvscode-server only being available on localhost, but it is actually publicly accessible.

Please consider showing the actual bound address, or add an extra message, like:

```
Server listening on 0.0.0.0:3000
Web UI available at http://localhost:3000
```

---

This is tested on the 8b3e975958809f5c058e2c07b60581a588aca481 prelease:
https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-nightly-v1.61.0

**Comment by jeanp413** [comment]
@afq984 Now that we are using the upstream server implementation, you should create an issue in the upstream vscode repo.

Closing this, thanks.
