### ISSUE TITLE
Please add some description about relationship to cdr/code-server

### ISSUE THREAD

**Issue by MaciejKucia** [gitpod-io/openvscode-server#112]
Hello, thank you for this great project.

I am a bit confused about how this relates to https://github.com/cdr/code-server. 

Are the openvscode-server and code-server both forks of vscode that try to achieve the same goal of having vscode in the browser? Or is it more to it?

Thanks!

**Comment by SitramSoft** [comment]
I would also be interested in the what is different between this project and https://github.com/cdr/code-server. I'm running code-server on a headless linux VM for almost a year, and I'm thinking to give this project a try. Would love to get a comparison between these two if one is available somewhere online.

**Comment by dnsmichi** [comment]
https://twitter.com/jolandgraf/status/1442850063953313805?s=20 has insights in the thread. cc @JohannesLandgraf 

> With nightly builds OpenVSCode Server is as upstream to code
 as possible and in contrast to other forks only adds a minimal set of changes (specifics about what we added https://bit.ly/3ibFRWQ).

> The architecture we use powers Gitpod and Github codespaces. Several of the devs and orgs that asked for our implementation & now have adopted OpenVSCode Server referenced the following issue https://bit.ly/3og3UHG. Folks should compare & use what works best for them Raising hands

and https://twitter.com/GeoffreyHuntley/status/1442964245461700609?s=20 cc @ghuntley 

> OpenVSCode-Server has absolute minimal changes to it so that you, I and the world can use the exact same version of vscode as used on Gitpod and GitHub Codespaces on your local computer (or in your own product)
>
> Updated and released nightly and doesn't have fork issues

**Comment by dnsmichi** [comment]
https://github.com/cdr/code-server/discussions/4267#discussioncomment-1411583

**Comment by dnsmichi** [comment]
https://github.com/gitpod-io/openvscode-server/issues/123 cc @mikenikles

**Comment by MaciejKucia** [comment]
Closing as #123 is more comprehensive and will cover this request. Thanks again!
