### ISSUE TITLE
https Proxy support to avoid port number in favor of subdomains

### ISSUE THREAD

**Issue by WarDrake** [gitpod-io/openvscode-server#113]
I'd like to see support for subdomain proxies instead of exposing ports on the URL and server
https://vscode.example.com is much preferable than http://exmaple.com:3000
especially when running it for teams.

**Comment by akosyakov** [comment]
You should be able to install reverse proxy in front and configure it to serve on sub domain.

I don’t think it has to be built in in the server. We do the same at Gitpod.
