### ISSUE TITLE
What is the default websocket port for the linux deployment?

### ISSUE THREAD

**Issue by driftywinds** [gitpod-io/openvscode-server#115]
Since OSS runs on the machine locally and is not available on the internet, I decided to use the nginx reverse proxy to make the webpage available, but in my config I used the port 3000 for the websocket and the site keeps telling me to reload with a "websocket error 1006". I think the problem here is that the right port for the websocket hasn't been configured, but I don't know which port it is, so I was wondering if anyone could help me out?
Running Ubuntu 20.04

**Comment by TheColin21** [comment]
same problem here

**Comment by TheColin21** [comment]
I'm getting the same error message running in Docker on Ubuntu 20.04 with Nginx as reverse proxy.

**Comment by arbob** [comment]
I'm getting the same error. Running on EC2 Ubuntu with Apache as reverse proxy.

**Comment by starmadegeek** [comment]
Same error on EC2 Ubuntu 20.04 with Apache

**Comment by starmadegeek** [comment]
You should add support for websockets by adding this line in apache2 config.

`       RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule ^/?(.*) "ws://localhost:3000/$1" [P,L]`

also make sure that you have the `proxy_wstunnel ` apache module enabled.

Check [this](https://github.com/gitpod-io/openvscode-server/discussions/96#discussioncomment-1404354) discussion for more info. I guess the same solution can also be applied to Nginx.

**Comment by driftywinds** [comment]
> You should add support for websockets by adding this line in apache2 config.
> 
> ```
>         RewriteCond %{HTTP:Upgrade} websocket [NC]
>         RewriteCond %{HTTP:Connection} upgrade [NC]
>         RewriteRule ^/?(.*) "ws://localhost:3000/$1" [P,L]
> ```
> 
> also make sure that you have the `proxy_wstunnel ` apache module enabled.
> 
> Check [this](https://github.com/gitpod-io/openvscode-server/discussions/96#discussioncomment-1404354) discussion for more info. I guess the same solution can also be applied to Nginx.

Hi sorry, I do not know how to implement this onto the nginx config

**Comment by starmadegeek** [comment]
It works fine for me. Can you share the contents of your config file. It should look like the one in discussion I mentioned above. Also what version of Apache2 are using? It should be >= 2.4.48. If not, update it using secondary PPA as debian PPA doesnot contain the latest version yet.

**Comment by driftywinds** [comment]
> It works fine for me. Can you share the contents of your config file. It should look like the one in discussion I mentioned above. Also what version of Apache2 are using? It should be >= 2.4.48. If not, update it using secondary PPA as debian PPA doesnot contain the latest version yet.

Okay, I checked, it was a cookie issue for the webpage, but after loading I still get the websocket error. I am going to copy the exact config from your reply above and try it. Will update soon

**Comment by jeanp413** [comment]
Closing this as the conversation can continue on the linked github discussion.
Thanks!
