### ISSUE TITLE
Documentation: Global User Settings

### ISSUE THREAD

**Issue by oldirtybasti** [gitpod-io/openvscode-server#129]
Where does one have to put the settings.json (global user settings) when building a docker image based on your image?

When using $HOME/.config/Code/User/settings.json as stated in the vscode documentation the settings get ignored

**Comment by jeanp413** [comment]
User settings are stored in the browser, there's Machine settings which are located in `~/.opencode-server/Machine/settings.json`

**Comment by oldirtybasti** [comment]
can the default user-settings in the browser somehow be set?
