### ISSUE TITLE
Add —help to improve discoverability of configuration options

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/openvscode-server#137]
```
./server.sh —help
```

Should display all configuration options from https://github.com/gitpod-io/openvscode-server/blob/aa211ec893de214588c6955d15d325aa03bae60d/src/vs/server/node/server.main.ts#L316

**Comment by lowski** [comment]
Just having a doc that list all available options in guides would be a good starting point (IMHO). At the moment it's difficult to find that it's possible to set port or token.

**Comment by akosyakov** [comment]
For adding `help` please open the issue in the upstream: https://github.com/microsoft/vscode We are not going to change the server.

Adding docs is welcomed.

**Comment by aptalca** [comment]
Right, so is there a list of available options anywhere?
Going through the various code and docs, I see `port`, `connectionToken` and `connectionSecret`. Any others?
Thanks

**Comment by filiptronicek** [comment]
@aptalca you can find all of them here: 
https://github.com/microsoft/vscode/blob/27a61bd9852cb8b808af99f0acedd3b5d3b9afd5/src/vs/server/serverEnvironmentService.ts#L12-L59

**Comment by filiptronicek** [comment]
This has been implemented in the upstream, `--help` should be working just fine (if it doesn't, please raise an issue!) 🙂
![image](https://user-images.githubusercontent.com/29888641/150639757-e6dcd2bf-0eb6-4134-9977-dd6b4ef23b3b.png)
