### ISSUE TITLE
Terminal fonts

### ISSUE THREAD

**Issue by veritem** [gitpod-io/openvscode-server#140]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.2
- OS Version: Windows 

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/53856673/136171262-a9e038d4-680d-4b5f-9fe4-3868bddb07f4.png)

The font in the terminal is broken. I've tried to change the font family in settings,but nothing seems to work

**Comment by akosyakov** [comment]
please check out discussions here: https://github.com/gitpod-io/gitpod/issues/5014
