### ISSUE TITLE
OpenVSCode-Server - Run/Debug with Launch configuration broken

### ISSUE THREAD

**Issue by jebuselwyn** [gitpod-io/openvscode-server#151]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.60.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Create a custom launch-configuration - e.g Java
2. Try running the program choosing the launch config. It fails to pick the configuration from the launch.json and in-turn asks for selection of type (Chrome/Node/Java)..
3. The same feature works fine when using the VSCode+Remote Ssh feature (on same workspace).
4. Additionally, if you have any other file open - (e.g json / xml file), the launcher gives and error ("You don't have an extension for debugging 'JSON with Comments'. Should we find a 'JSON with Comments' extension in the Marketplace?")

**Comment by akosyakov** [comment]
Yes, there were a regression in upstream, please use 1.60.2 or better 1.61.
