### ISSUE TITLE
Add authentication Option

### ISSUE THREAD

**Issue by nWhitehill** [gitpod-io/openvscode-server#153]
I would love to contribute a new feature where you can deploy this server with the option to have it serve up an Oauth splash screen before allowing a user to go to the workspace. Only authenticated users would be allowed to use the workspace in this use case. Additionally or optionally, adding the option to force a user to provide a password before going to the workspace.

I would love the chance to contribute to this project but want to make sure this feature would be welcomed by the community / maintainers before spending too much time on it.

**Comment by andymac4182** [comment]
@akosyakov Would a better option be to look at providing the hooks for people to integrate their own auth. It feels like auth is something that multiple users of this would like to have and would be nice to have a semi standard way of integrating that auth into the project.

**Comment by michaellilltokiwa** [comment]
@andymac4182 what kind of hooks are you thinking about? I don't think it is necessary/reasonable to integrate hooks for auth in this project.

@akosyakov +1 for keeping this as close as possible to the official vscode repo.
