### ISSUE TITLE
Add Fonts?

### ISSUE THREAD

**Issue by TheAlphaReturns** [gitpod-io/openvscode-server#166]
How would I like to add a font to the Terminal? I tried installing it from the docker deployment, as I would on any other Linux machine (and I even verified it was there using `fc-list`.) Changing the font-face in settings made the terminal font all weird (definitely NOT the one I wanted)

How would I add a font? is there a workaround if it is not a feature yet. I know that on cdr/code-server, you can edit some HTML to add a `@font-face`.

I also don't have access to the developer tools menu (blocked by admin).

**Comment by akosyakov** [comment]
As far as I know browser should be aware of fonts, so you have to install on local machine.
