### ISSUE TITLE
Unable to set default Application User settings

### ISSUE THREAD

**Issue by spkane** [gitpod-io/openvscode-server#198]
### Bug description

I am installing `openvscode-server` on an Ubuntu server and am trying to set some of the default User settings, so that all session have these set by default.

In particular I'd like to set these four:

```json
{
  "update.mode": "none",
  "telemetry.telemetryLevel": "off"
  "extensions.autoCheckUpdates": false,
  "extensions.autoUpdate": false
}
```

**NOTE**: These are not `remote` or `workspace` settings, but specifically `user` settings.

I can easily set them in a running session, but can not figure out a way to make these the default behavior for all sessions.

### Steps to reproduce

1) Try to create a file somewhere (e.g. `~/.openvscode-server/user-data/User/settings.json`) with the following contents.

```json
{
  "update.mode": "none",
  "telemetry.telemetryLevel": "off"
  "extensions.autoCheckUpdates": false,
  "extensions.autoUpdate": false
}
```

2) Start openvscode-server.

3) Open up and IDE session and check to see if these settings are set as defined in the settings file.

### Expected behavior

It should be possible to feed in a default set of Application User settings that will be used for all session, and can then be modified by the user for their active session.

**Comment by akosyakov** [comment]
VS Code Web does not store settings on the disk, but in browser indexed DB per a origin. You will need to open it via User Settings and change there. After that they will be the same for any workspace which you open from such origin. If you change origin then settings won't be there.
