### ISSUE TITLE
Is it possible to disable security token?

### ISSUE THREAD

**Issue by xawlw** [gitpod-io/openvscode-server#207]
As mentioned in https://github.com/gitpod-io/openvscode-server/commit/4575b989a97668904eb76fcc8a25665c5958eecf
I would like to disable this feature as my openvscode server is already protected by basic HTTP authentication

**Comment by oldirtybasti** [comment]
If the token cannot be disabled it would be good to at least have the possibility to set this token. Otherwise all browser links are obsolete after the container is started again

**Comment by JeDaYoshi** [comment]
This is a deal-breaker in my use-case, so it'd be pretty great if this requirement from VS Code Server would be removed or can be toggled.

**Comment by xawlw** [comment]
Ok so I’m closing this as apparently we can set a fixed token,
More details can be found here https://github.com/gitpod-io/openvscode-server/pull/206/commits/c67d0aff73590fc22e5322b557b25999afd24b28

Although I would prefer to have a toggle to disable the feature completely, but setting a fixed token will do the job for me.

**Comment by akosyakov** [comment]
It will require code changes in the server. We would like to avoid it. Please set the fixed token. Alternative propose a PR in the upstream.

**Comment by filiptronicek** [comment]
Created https://github.com/microsoft/vscode/issues/136615 to track the progress on this.
