### ISSUE TITLE
Inconsistency in usage when it comes to port 3000

### ISSUE THREAD

**Issue by gbraad** [gitpod-io/openvscode-server#219]
The latest release v1.62.0 defaults to port `8000` when used with `./server.sh` and documentation still takes about port `3000`. While the Docker image, correctly stated in the documents, uses port `3000`.

It might be a suggestion to add `--port 3000` to the server.sh file for the release, just like is done for the Docker image.

**Comment by gbraad** [comment]
`Dockerfile` states:
https://github.com/gitpod-io/openvscode-releases/blob/e276c8152b9d04e6ac410fae3bf7686af48e5d6f/Dockerfile#L45
which overrides the port as it passes this on.

While the script:
https://github.com/gitpod-io/openvscode-server/blob/0c19763de43d84cef99fc99c63d8cf4d9557014c/resources/server/bin/server.sh#L12
does not provide a default,

Readme talks about 3000:
https://github.com/gitpod-io/openvscode-server/blob/0c19763de43d84cef99fc99c63d8cf4d9557014c/README.md?plain=1#L59
which is therefore not the case.

**Comment by gbraad** [comment]
```patch
-"$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
+"$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@" --port ${PORT:-3000}
```

**Comment by jeanp413** [comment]
@akosyakov what do you think, should we just update the readme or set the port to 3000 in the script?

**Comment by akosyakov** [comment]
@jeanp413 If we can update script conflict free with upstream then it will be easier.
