### ISSUE TITLE
server.sh failed: No such file or directory

### ISSUE THREAD

**Issue by stuartmaxwell** [gitpod-io/openvscode-server#227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.62.2 or latest or insiders
- OS Version: Docker on Ubuntu

Steps to Reproduce:

1. Run docker image, e.g. `docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server`
2. Get the following error:
```bash
docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server
[FATAL tini (7)] exec ${OPENVSCODE_SERVER_ROOT}/server.sh failed: No such file or directory
```
3. The same behaviour occurs with any of the following tags: `insiders`, `latest`, `1.62.2`
4. This does not happen when using the following tag: `1.62.0`

Hope that helps.

Cheers,
Stuart

**Comment by jimmybrancaccio** [comment]
We just noticed this on Discord too (https://discord.com/channels/816244985187008514/892384683273388062/909891245898354799). I noticed that you can run the `server.sh` file manually and that seems to work fine:

```
$ docker run -it --entrypoint /bin/bash -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server:1.62.2

$ openvscode-server@b2611ec1ed57:/home/openvscode-server-v1.62.2$ echo $OPENVSCODE_SERVER_ROOT
/home/openvscode-server-v1.62.2
$ cd /home/openvscode-server-v1.62.2
$ openvscode-server@b2611ec1ed57:/home/openvscode-server-v1.62.2$ ./server.sh --port 3000
Extension host agent listening on 3000

Web UI available at http://localhost:3000/?tkn=104f2239-b848-4a32-b3f6-3014a1d6783c
[19:59:32] Extension host agent started.
```

**Comment by jeanp413** [comment]
Thanks for reporting, taking a look right now

**Comment by jeanp413** [comment]
Docker images are working again :tada: , thanks!
