### ISSUE TITLE
Is there a way to disable auth token?

### ISSUE THREAD

**Issue by sevilen** [gitpod-io/openvscode-server#230]
sometimes, I don't need to use a token. Is there a way to turn off the token?

  Add options to startup script, like `--auth none`

**Comment by shyd** [comment]
I agree, my environment is protected with caddy and pomerium. In this scenario I don't need a token. I don't even know it when launching the site on an iPad or any other device.

**Comment by filiptronicek** [comment]
Hi there, I'm closing this in favor of #224, this is currently being worked on by the VS Code team at Microsoft, if you want to give them a little push feel free to give a 👍 to https://github.com/gitpod-io/openvscode-server/discussions/224#discussioncomment-1633259.
