### ISSUE TITLE
Web: Translations not supported

### ISSUE THREAD

**Issue by CinaStan** [gitpod-io/openvscode-server#231]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.62.2
- OS Version: ubuntu 20

Steps to Reproduce:

1.
2.

**Comment by jeanp413** [comment]
@CinaStan currently translations are not supported for vscode web. Related upstream issue https://github.com/microsoft/vscode/issues/82595

**Comment by akosyakov** [comment]
Please track upstream issue.
