### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by oakaigh** [gitpod-io/openvscode-server#232]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.62.2` (current)
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Run `yarn gulp server-min` [as described in the `docs`](https://github.com/gitpod-io/openvscode-server/blob/docs/development.md).
2. Says `Task never defined`.
3. Inspected the `/build` folder. Found `gulpfile.server.js` missing.

What command am I supposed to use to build the current version of this project from source? The `gulpfile`s all seem to come from the upstream now.

**Comment by jeanp413** [comment]
@oakaigh thanks for reporting, I'll create an issue regarding the outdated `development.md`.
To build the release version you need to run the following command:
```
yarn gulp vscode-reh-web-linux-x64-min
```
This task is defined in `build/gulpfile.reh.js`
