### ISSUE TITLE
Jupypter notebook with markdown cell not loading

### ISSUE THREAD

**Issue by oakaigh** [gitpod-io/openvscode-server#233]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.62.0` `1.62.2`
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Download server from https://github.com/gitpod-io/openvscode-server/releases.
2. Run server on `localhost`.
2. Install Jupyter Notebooks and extensions.
2. Open an `.ipynb` file (it should contain a markdown cell) at `http://localhost:8000/`.
3. File unable to load: `Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://vscode-remote+localhost-003a8000.vscode-resource.vscode-webview.net/<openvscode-server-path>/extensions/markdown-language-features/notebook-out/index.js`.
4. Add `extensions/markdown-language-features/notebook-out` from project built from source.
5. Reload window.
6. File starts loading.

**Comment by jeanp413** [comment]
@oakaigh Thanks for reporting, I can reproduce :+1:

**Comment by jeanp413** [comment]
This is now fixed in insiders release
