### ISSUE TITLE
`PATH` environment variable not inherited from the parent process

### ISSUE THREAD

**Issue by oakaigh** [gitpod-io/openvscode-server#237]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.62.2`
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Execute `printenv PATH` in the current terminal. Output includes the standard `bin` directories.
2. Run
```sh
node -e 'require(`child_process`).spawnSync(`<path-to-server-sh>`, [], { env: {}, stdio: `inherit` })'
```
2. Open the `http://localhost:8000/?tkn=<connection-token>` link as instructed.
3. Toolbar: `Terminal` > `New Terminal`
4. Execute `printenv PATH`. Standard `bin` directories missing from the output.

**Comment by jeanp413** [comment]
Closing as pointed in https://github.com/gitpod-io/openvscode-server/pull/238#issuecomment-1029843414. Let me know if it's still an issue
