### ISSUE TITLE
WebViews are not displayed in server mode

### ISSUE THREAD

**Issue by johnpaliotta** [gitpod-io/openvscode-server#253]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: openvscode-server-v1.62.3
- OS Version:  Ubuntu 20.04.1 LTS

I am using vscode.window.createWebviewPanel to create a webview and display some static HTML.  Everything works fine with the desktop version, but in the server version I get a blank document.  To try to figure out what's going on I switched to the webview-sample (cat coding) and reproduced the problem

Steps to Reproduce:

1. Built the webview-sample using vsce package on windows
2. Moved the resultant .vsix file to linux
3. Downloaded the vscode-server from https://github.com/gitpod-io/openvscode-server/releases
4. Started the vscode-server, using ./server.sh
5. Connected to the server using Chrome (I tried Firefox too)
6.  Installed the .vsix
7. Ran command: "Cat Coding: Start cat coding session"
8. Empty tab appears

**Comment by jeanp413** [comment]
@johnpaliotta I cannot reproduce, I'm on ubuntu 21.10. Do you see any relevant error in the dev tools console?
![image](https://user-images.githubusercontent.com/25115070/144908477-08c6e17f-3fe4-4652-b04c-7ad3717a593f.png)

**Comment by johnpaliotta** [comment]
@jeanp413 thanks for the quick reply.
In the developer console I see these errors
![image](https://user-images.githubusercontent.com/5348977/144918308-ab9b1240-ec1c-4fb7-9f93-2edf338e0321.png)

I searched around a bit and it seems that a cause can be using http vs https, but I could not find an clear description on how to switch this.

Since I am on a Linux VM as the host, I installed Chrome and then used the http://localhost* to connect.  Now, the cat coding and my extension work fine, so thanks for the tip about the developer console.

On the other hand I would still like to be able to connect from a remote machine so if anyone has info on how to use https in this context I would appreciate it.

**Comment by jeanp413** [comment]
I see, yeah for webviews to work you'll need https or localhost. For https to work on a remote machine you'll need to setup a reverse proxy (ngix or apache2), you can check this discussion with an apache2 config https://github.com/gitpod-io/openvscode-server/discussions/96#discussioncomment-1410639

**Comment by johnpaliotta** [comment]
Ok will try to get that going tomorrow ... thanks again
