### ISSUE TITLE
The language pack extension cannot be installed, Is it possible to replace the default language during the build?

### ISSUE THREAD

**Issue by sevilen** [gitpod-io/openvscode-server#261]
Unable to install language pack in openvscode-server. For some beginners, they may need localization to learn how to use vscode.

Can I build with language packs built in?

**Comment by sevilen** [comment]
I found the following code in `src/vs/node/languagePacks.js`
```javascript
function getLanguagePackConfigurations(userDataPath) {
	const configFile = path.join(userDataPath, 'languagepacks.json');
	try {
		return nodeRequire(configFile);
	} catch (err) {
		// Do nothing. If we can't read the file we have no
		// language pack config.
	}
	return undefined;
}
```
What should be included in languagepacks.json？

**Comment by jeanp413** [comment]
@sevilen currently translations are not supported for vscode web. Related upstream issue microsoft#82595

**Comment by sevilen** [comment]
@jeanp413 Ok, I got it, thanks for your reply.

**Comment by wzxinchen** [comment]
https://github.com/microsoft/vscode-nls/pull/42

Does the pr as above can support chinese? If so , what should I do?

**Comment by jeanp413** [comment]
Not possible yet sadly.
Language packs extensions are not used for web, instead some json file is used and is hosted in MS servers and the endpoint is configured in `product.json` and as far as I know we cannot legally use the MS endpoint in our `product.json`.
I think we can somehow derive from the extensions the needed json files and host it ourselves in the future, this will only apply for the workbench localization. For extensions localization, I created an issue about it https://github.com/microsoft/vscode/issues/152403 as some scripts are required to generate the localization files
