### ISSUE TITLE
Allow the capability to disable the token authentication

### ISSUE THREAD

**Issue by routerino** [gitpod-io/openvscode-server#266]
I protect my Vscode environment behind https, an oauth proxy and single sign on server. Having the token authentication on top of that is unnecessary and causes headaches when it comes to automating dev environment provisioning.

**Comment by filiptronicek** [comment]
Hi there, I'm closing this in favor of #224, this is currently being worked on by the VS Code team at Microsoft, if you want to give them a little push feel free to give a 👍 to https://github.com/microsoft/vscode/issues/136615.

**Comment by routerino** [comment]
> Hi there, I'm closing this in favor of #224, this is currently being worked on by the VS Code team at Microsoft, if you want to give them a little push feel free to give a 👍 to [microsoft#136615](https://github.com/microsoft/vscode/issues/136615).

Thanks, was not aware this is an upstream issue.
