### ISSUE TITLE
Whitelist  .NET Interactive Notebooks for access to Proposed APIs

### ISSUE THREAD

**Issue by ndgayan** [gitpod-io/openvscode-server#267]
.NET Interactive Notebooks are not working. Could you add this feature to the OpenVSCode Server?

![Feature Request](https://user-images.githubusercontent.com/1891059/146687048-306b3830-613f-4596-b259-fd7332315a71.png)

A similar extension issue has already been discussed [here](https://github.com/gitpod-io/openvscode-server/issues/170).

**Comment by jeanp413** [comment]
Sure I guess I'll go ahead and enable proposed API by default, no need to be restrictive like upstream cc @akosyakov

**Comment by akosyakov** [comment]
If it does not imply more rebase conflicts then fine.

**Comment by jeanp413** [comment]
@ndgayan can you test this in insiders? it should be enable by default now

**Comment by jeanp413** [comment]
closing this as it got fixed in 860e13b5b824b22b20881e2f9f478ff1c77dafef
