### ISSUE TITLE
style auth screen

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/openvscode-server#27]
For stock Code Server we need the auth screen which is basically an input form with one password field.

**Comment by svenefftinge** [comment]
make it juicy (kumquaty)

**Comment by moizhusnain** [comment]
bump! adding a simple auth screen to the code will be a great idea. Specifically in cases where the developers are deploying it to ec2 / vm.

**Comment by akosyakov** [comment]
We are not doing it in this repo since it will deviate from the upstream issue. it could be done by downstreams though-
