### ISSUE TITLE
Github authentication is getting 403 forbidden....

### ISSUE THREAD

**Issue by abhijeet-1110** [gitpod-io/openvscode-server#270]
Hi Team,

I am unable to authorize the GitHub authentication.It is getting 403 forbidden after clicking the authorize button.

![Screenshot from 2021-12-21 15-40-50](https://user-images.githubusercontent.com/69045486/146912904-2a9dcc89-2008-41f8-ac75-95da13fdb8ab.png)
![Screenshot from 2021-12-21 15-41-34](https://user-images.githubusercontent.com/69045486/146912900-32b320bd-a774-4378-ad15-c171d4f7b073.png)
![Screenshot from 2021-12-21 15-41-42](https://user-images.githubusercontent.com/69045486/146912897-69ca5a8d-a41f-4d29-8a7a-f99919d3a908.png)

**Comment by filiptronicek** [comment]
Hi @abhijeet-1110, thanks for raising this issue. This is currently not possible because only the builds from Microsoft can have this GitHub and Microsoft login flow. 

Closing this in favor of #127
