### ISSUE TITLE
can not accurate open big file

### ISSUE THREAD

**Issue by cws999** [gitpod-io/openvscode-server#275]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.63
- OS Version:devuan 4

Steps to Reproduce:

1.A file with a size of 750MB, vscode opened for a few seconds. But openvscode-server opens and uses for more than a minute. It's running too slowly, what is it doing？
2.

**Comment by filiptronicek** [comment]
Hey there @cws999, you should check the browser console, I think there is a high chance of VS Code just transferring the whole file to your browser, which, depending on your internet speed may take a long time if it's such a big file. Please try this with smaller files (sizes that are reasonable to transfer over your connection) and please let me know if they eventually load or not!

**Comment by cws999** [comment]
> 
Both large files and small files can be loaded, but large files take a long, long time to load.
I use it locally, no network required. I'm not a programmer and only use and describe things. I don't know how to debug

**Comment by akosyakov** [comment]
I think it should be reported in https://github.com/microsoft/vscode

**Comment by cws999** [comment]
> 

[microsoft/vscode](https://github.com/microsoft/vscode)no such case
