### ISSUE TITLE
How to map the service to designated ip and port on linux?

### ISSUE THREAD

**Issue by sqiangcao99** [gitpod-io/openvscode-server#280]
When I follow this instruction to run vscode on linux, I found the service is set up on localhost:3000 that I couldn't directly access. Can openvscode be set up on the designated ip and port？ 
```
tar -xzf openvscode-server-v${OPENVSCODE_SERVER_VERSION}.tar.gz
cd openvscode-server-v${OPENVSCODE_SERVER_VERSION}
./server.sh
```

**Comment by filiptronicek** [comment]
Hey there, @sqiangcao99! You may be interested in https://github.com/gitpod-io/openvscode-server/discussions/96 or https://github.com/gitpod-io/openvscode-server/discussions/252, depending on what you mean by "can't directly access". Hope it helps!
