### ISSUE TITLE
Base Image on Ubuntu 20

### ISSUE THREAD

**Issue by oldirtybasti** [gitpod-io/openvscode-server#286]
currently the docker image is based on Ubuntu 18.04, which is quite dated. Is it possible to upgrade the image to ubuntu 20?

**Comment by augustoicaro** [comment]
Hello @oldirtybasti,

As you can see https://github.com/gitpod-io/openvscode-releases/pull/13/files this update is simple to do. So you can use the official Dockerfile with ubuntu version change, and all will work as expected.

**Comment by jeanp413** [comment]
closing this as https://github.com/gitpod-io/openvscode-releases/pull/13/files is merged
