### ISSUE TITLE
Setting up in Raspberry Pi 4 Model B with docker failed

### ISSUE THREAD

**Issue by ql-isaac** [gitpod-io/openvscode-server#293]
Steps to Reproduce:
```bash
docker run -it --init -p 3000:3000 -v "$(pwd):/home/workspace:cached" gitpod/openvscode-server
```
```text
Unable to find image 'gitpod/openvscode-server:latest' locally
latest: Pulling from gitpod/openvscode-server
latest: Pulling from gitpod/openvscode-server
0fe312f6db8a: Pull complete 
e9f512030797: Pull complete 
3e505cb77d29: Pull complete 
356502121575: Pull complete 
d47743eb0865: Pull complete 
Digest: sha256:9a1ae6fba964367666872ac6ce430a3e622574e50692f9a435b65438d15621bc
Status: Downloaded newer image for gitpod/openvscode-server:latest
/home/openvscode-server-v1.63.2/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```
```bash
sudo docker ps -a
```
```text
CONTAINER ID   IMAGE                      COMMAND                  CREATED              STATUS                            PORTS     NAMES
7be8c7554c83   gitpod/openvscode-server   "/bin/sh -c 'exec ${…"   About a minute ago   Exited (127) About a minute ago             serene_mestorf
```

**Comment by stemount** [comment]
Possibly related to https://github.com/gitpod-io/openvscode-server/issues/239 - not sure that there is full support for ARM64 but I'll check it out tomorrow to see where this is at.

**Comment by filiptronicek** [comment]
Hey there @ql-isaac, thanks for taking the time to report this bug. I've googled the error and stumbled upon https://github.com/cui-unige/outils-formels-modelisation-2018/issues/39 - maybe we need to include hat shared dependency in our Docker image. Could you please try to add

```Dockerfile
RUN apt-get install libatomic1
``` 
to this Dockerfile, try to build it and run it on your rPi?

**Comment by ql-isaac** [comment]
> Hey there @ql-isaac, thanks for taking the time to report this bug. I've googled the error and stumbled upon [cui-unige/outils-formels-modelisation-2018#39](https://github.com/cui-unige/outils-formels-modelisation-2018/issues/39) - maybe we need to include hat shared dependency in our Docker image. Could you please try to add
> 
> ```dockerfile
> RUN apt-get install libatomic1
> ```
> 
> to this [Dockerfile](https://github.com/gitpod-io/openvscode-releases/blob/ac92fddf53feef1e8f3692cacdcd911051457ab9/Dockerfile#L12), try to build it and run it on your rPi? I would do this myself but I don't have a Pi 4 available to me.

Great,I will try after a while.It's normal that setting up with running the server directly,so I think it just because of this.

**Comment by ql-isaac** [comment]
> Hey there @ql-isaac, thanks for taking the time to report this bug. I've googled the error and stumbled upon [cui-unige/outils-formels-modelisation-2018#39](https://github.com/cui-unige/outils-formels-modelisation-2018/issues/39) - maybe we need to include hat shared dependency in our Docker image. Could you please try to add
> 
> ```dockerfile
> RUN apt-get install libatomic1
> ```
> 
> to this [Dockerfile](https://github.com/gitpod-io/openvscode-releases/blob/ac92fddf53feef1e8f3692cacdcd911051457ab9/Dockerfile#L12), try to build it and run it on your rPi? I would do this myself but I don't have a Pi 4 available to me.

Thank you very much.It's working！

**Comment by filiptronicek** [comment]
We should update the Dockerfile to include the dependency, I'll add it as soon as I get the chance.

**Comment by whschultz** [comment]
Any updates?  This still appears to be a current issue.

**Comment by filiptronicek** [comment]
Fixed in https://github.com/gitpod-io/openvscode-releases/commit/66d6efb275fe1b954c194b7c196b652c2d408a76 :)
