### ISSUE TITLE
Remote Explorer should sort ports in numerical order

### ISSUE THREAD

**Issue by chuck-confluent** [gitpod-io/openvscode-server#298]
I made an issue in the gitpod project but it might actually belong here. I would like the remote explorer to show ports in numerical order or in the order I specify in the .gitpod.yml file

- https://github.com/gitpod-io/gitpod/issues/7764

**Comment by jeanp413** [comment]
Hi @chuck-confluent, it actually belongs to gitpod repo, I'll reopen the issue there thanks for reporting this.
