### ISSUE TITLE
Missing `server.sh` on latest insiders `openvscode-server-insiders-v1.64.0`

### ISSUE THREAD

**Issue by francisschmaltz** [gitpod-io/openvscode-server#300]
Latest insiders build missing `server.sh`. Trying to test `--without-connection-token` in latest insiders build but package is missing entry point

- VS Code Version: openvscode-server-insiders-v1.64.0
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. `wget https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-insiders-v1.64.0/openvscode-server-insiders-v1.64.0-linux-x64.tar.gz`
2. `tar -xzf openvscode-server-insiders-v1.64.0-linux-x64.tar.gz`
3. `cd openvscode-server-insiders-v1.64.0-linux-x64`
4. `./server.sh`

**Comment by filiptronicek** [comment]
I will keep this issue open until the README is correct about the behavior.

**Comment by francisschmaltz** [comment]
Thanks @filiptronicek! I can confirm that running `./bin/openvscode-server` works! Thanks for linking the docs as well
