### ISSUE TITLE
Cannot run out/vs/server/main.js without development mode

### ISSUE THREAD

**Issue by rotemso** [gitpod-io/openvscode-server#301]
Hello,
I'm trying to build and run openvscode-server (from tag openvscode-server-v1.63.2) from my own docker image.
I'm cloning this git repository with the specified tag, and then building using:
```
yarn
yarn server:init
```
Then I'm running openvscode-server using: 
``` node $ROOT/out/vs/server/main.js --port=3000```

Then when I'm trying to access http://localhost:3000 the application is not loaded, and I see the following error in the browser console log:
```
loader.js:1384 Uncaught Error: Can only have one anonymous define call per script file
    at ModuleManager.enqueueDefineAnonymousModule (loader.js:1384:23)
    at DefineFunc (loader.js:1871:27)
    at workbench.js:5:1
```
The same happens also when trying to access with the token specified in the server output.

When I try the same with defining the following environment variables before running:
```
ENV NODE_ENV=development
ENV VSCODE_DEV=1
```
the application is loaded from http://localhost:3000 (with no token) as expected, but then I see the "dev" string everywhere and also loading time of the web application is quite long as seems that resources / scripts are loaded one by one and not as a minified / bundled form.

How can I run the openvscode-server in "production" mode (with no dev environment variables)?
How to ensure running the web UI with a minified / bundled form (for fast loading)?
Is there some flag that enables running without token validation?

Your assistance is much appreciated.

Thanks,
Rotem

**Comment by filiptronicek** [comment]
Hey there @rotemso! If you want to run the development mode, please use the commands specified here: https://github.com/gitpod-io/openvscode-server/blob/cd2a8249fdac13b6136b8df0ddedd05d8ff97047/.gitpod.yml#L14 and if you want to build from source, see https://github.com/gitpod-io/openvscode-server/blob/docs/development.md#building.

If you have trouble with setup, try installing the same dependencies or using our Docker image we use for development: https://github.com/gitpod-io/openvscode-server/blob/main/.gitpod.Dockerfile.

Let me know if you have any issues 🙂

**Comment by rotemso** [comment]
Thank you @filiptronicek - the `yarn gulp vscode-reh-web-linux-x64-min` was exactly what I was looking for (as I didn't want to run in development mode, but only in production mode).

With that, I have noticed that when building the project this way in version 1.63.2 I must use a connection token. 
Since I noticed that the there is a new flag of --without-connection-token in version insiders-v1.64.0 I have tried to switch to this one, but the latest tag seem to be broken (when trying to access localhost:<port> I get the following error:
``` localhost didn’t send any data.
ERR_EMPTY_RESPONSE
``` 
I have also tried to download the official tar from here:
https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-insiders-v1.64.0/openvscode-server-insiders-v1.64.0-linux-x64.tar.gz
and result is the same.

Am I missing something or that this version is now broken?
(same tar downloaded few days ago before last commit was OK)

Can you please check?

Thanks!
Rotem

**Comment by filiptronicek** [comment]
@rotemso thanks for the heads up, I checked and cannot reproduce. This may be because the release is updated every day, so yours from 2 days ago is different from the one I just downloaded. With that said, could you please check again? If it is broken I'll investigate it further 🙂.

![image](https://user-images.githubusercontent.com/29888641/152397918-77710c24-a316-4694-96bf-f8056250488d.png)

**Comment by rotemso** [comment]
@filiptronicek just tested and current version seems ok - both in the released tar file and when building from source code in the relevant tag. Probably a temporarily issue that was slipped into one of the commits and already fixed.
Thanks for all your assistance! 
Closing this issue.
