### ISSUE TITLE
Docker nightly builds : Use "--without-connection-token" instead of "--connection-token 00000" for the entrypoint 

### ISSUE THREAD

**Issue by lodup29** [gitpod-io/openvscode-server#302]
Inspection of the [nightly builds](https://hub.docker.com/r/gitpod/openvscode-server) reveals that a fixed authentication token is used for the entry point
```
ARG ["-c", "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --connection-token 00000 \"${@}\"", "--"]
ENTRYPOINT ["/bin/sh", "-c", "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 ---connection-token 00000 \"${@}\"", "--"]
```
The switch _--without-connection-token_ was [recently introduced](https://github.com/microsoft/vscode/issues/136615). I think it would make sense to use this option instead for the nightly builds:
```
ARG ["-c", "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --without-connection-token \"${@}\"", "--"]
ENTRYPOINT ["/bin/sh", "-c", "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --without-connection-token \"${@}\"", "--"]
```

**Comment by anisimovdk** [comment]
gitpod-io/openvscode-releases#17

**Comment by jeanp413** [comment]
Fixed in https://github.com/gitpod-io/openvscode-releases/pull/17
