### ISSUE TITLE
Docker and version 1.64.0 not working with connectionToken option

### ISSUE THREAD

**Issue by nfrede** [gitpod-io/openvscode-server#306]
Since updating to 1.64.0 my docker installation stopped serving the website. After checking the logs it appears to be some type of change with how the connectionToken arguments are being handled.

I had to remove the connectionToken argument for now and it's working again.
 
Using docker compose command:
`command: '--connection-token <token>'`

Generates errors:
```
vscode  | Extension host agent listening on 3000
vscode  | 
vscode  | Option 'connectionToken' is deprecated: Use {0} instead.
vscode  | Please do not use the argument '--connection-token' or '--connection-token-file' at the same time as '--without-connection-token'.
```

Version:
```
OpenVSCode Server
Version: 1.64.0
Commit: 29c8370747ebb41bb0d41ebc495ee0894059548f
Date: 2022-02-04T09:54:01.707Z (15 hrs ago)
```

**Comment by jeanp413** [comment]
Hi @nfrede, starting version 1.64.0 we use the new `--without-connection-token` option by default so no token is required as usually openvscode-server is deployed behind a reverse proxy which already implements some kind of authentication.
If you still want to use the `--connection-token` option you can update the [Dockerfile](https://github.com/gitpod-io/openvscode-releases/blob/main/Dockerfile) or override the entrypoint in docker compose.

**Comment by nfrede** [comment]
Hey @jeanp413, thanks for the info! I was just confused as the readme still calls for use of the token flag and I didn't see anything mentioned in the releases. I'll just omit the token, not a big deal.

**Comment by jeanp413** [comment]
>  I was just confused as the readme still calls for use of the token flag and I didn't see anything mentioned in the releases

yes, sorry about that,  we'll update the readme in https://github.com/gitpod-io/openvscode-server/pull/299
