### ISSUE TITLE
Some extensions cannot be installed and used 

### ISSUE THREAD

**Issue by cws999** [gitpod-io/openvscode-server#313]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.65.0
- OS Version:devuan 4

Steps to Reproduce:

1.installed "ms-ceintl.vscode-language-pack-zh-hans"  [Install in Browser]  

2.error message  "The 'ms-ceintl.vscode-language-pack-zh-hans' extension is not available in code-server for Web."
3. .installed "moshfeu.diff-merge" 
4. Select two files to compare 
5. error message
`<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:b32cb1f4-501e-0075-15c7-2463b3000000 Time:2022-02-18T12:59:36.3559897Z
</Message>
</Error>`

But
These two extensions can be used correctly in Microsoft code

**Comment by filiptronicek** [comment]
Heya @cws999! I believe this is not a bug, rather intended behavior: some extensions are just not configured to run in the browser: some extensions are not available to be run in the browser, you can read more about it in the corresponding [VS Code Docs](https://code.visualstudio.com/api/advanced-topics/extension-host#preferred-extension-location).

With the Diff & Merge extension I could not reproduce your error, I am guessing maybe it's some TLS problems, are you using a self hosted OpenVSCode Server or how does your setup look like?
![image](https://user-images.githubusercontent.com/29888641/154700163-fa5e0a27-cf93-42d6-a726-5e028903e213.png)


Also, the extension you are trying to install is Microsoft's Chinese language pack. Translations are not yet a thing on the web, but they might be contributed by the wonderful @jsjoeio as means to resolve https://github.com/microsoft/vscode/issues/82595, so stay tuned, you will be available to do this, soon.

**Comment by jsjoeio** [comment]
> but they might be contributed by the wonderful @jsjoeio as means to resolve https://github.com/microsoft/vscode/issues/82595, so stay tuned, you will be available to do this, soon

Hoping I can get to that soon! No promises though 😅 Best to subscribe to that issue so you know when it's fixed upstream!

**Comment by cws999** [comment]
> With the Diff & Merge extension I could not reproduce your error, I am guessing maybe it's some TLS problems, are you using a self hosted OpenVSCode Server or how does your setup look like?

Does this issue occur when all extensions are disabled?: Yes

I am running the service locally like this 

[https://s3.bmp.ovh/imgs/2022/02/a71379ae58c16e19.jpg](url)
