### ISSUE TITLE
Extended details page  error display 

### ISSUE THREAD

**Issue by cws999** [gitpod-io/openvscode-server#314]
- VS Code Version:1.65.0
- OS Version:devuan 4

Steps to Reproduce:

1.Clicking on any of the extensions does not display the "Details" page and “Changelog" page
 2.looks like this 
<img src = 'https://s3.bmp.ovh/imgs/2022/02/c6d279a8036ffc12.jpg' />

**Comment by jeanp413** [comment]
@cws999 cannot repro do you see any error in browser console
![image](https://user-images.githubusercontent.com/25115070/154857754-3a6d32a0-40f1-4afa-a184-d5cde89858e7.png)

**Comment by cws999** [comment]
> @cws999 cannot repro, do you see any error in browser console

23:16:15.732 源映射错误：Error: request failed with status 404
源 URL：http://localhost:3000/static/out/vs/base/worker/workerMain.js#languageDetectionWorkerService
源映射 URL：https://ticino.blob.core.windows.net/sourcemaps/1d3f3da92c22bc201705d98391c1a9b891e31afd/core/vs/base/worker/workerMain.js.map

23:16:15.904 源映射错误：Error: request failed with status 404
源 URL：
源映射 URL：https://ticino.blob.core.windows.net/sourcemaps/1d3f3da92c22bc201705d98391c1a9b891e31afd/core/vs/workbench/services/languageDetection/browser/languageDetectionSimpleWorker.js.map

**Comment by jeanp413** [comment]
Those errors are unrelated to your issue with webviews.
If you open your dev tools in your browser in the network tab, you should see some requests similar to this `https://{some-uuid}.vscode-webview.net/insider/93a2a2fa12dd3ae0629eec01c05a28cb60ac1c4b/out/vs/workbench/contrib/webview/browser/pre/index.html'` when you click `Details` or `Changelog` page, they should return some html, are those successful?
