### ISSUE TITLE
Many extensions show "Reload required" button

### ISSUE THREAD

**Issue by idoprz** [gitpod-io/openvscode-server#318]
- VS Code Version: 1.64.2
- OS Version: 

Steps to Reproduce:
1. Open extensions panel
2. Type @popular to see popular extensions. Many extensions has "Reload required" button.

![image](https://user-images.githubusercontent.com/13120146/156554196-d8769841-e227-48e1-be49-e10a539f0733.png)

**Comment by jeanp413** [comment]
This is fixed in insiders and will also be fixed in next stable release 1.65 that will be released maybe today, most probably tomorrow. Thanks.
