### ISSUE TITLE
It seems that the path of the script `openvscode-server` has changed after v1.63.2?

### ISSUE THREAD

**Issue by ql-isaac** [gitpod-io/openvscode-server#332]
Before v1.63.2,path of the script `openvscode-server` is `bin/openvscode-server`,now It 's `bin/remote-cli/openvscode-server`.

**Comment by filiptronicek** [comment]
Hey there @ql-isaac, both of those files exist, but are a bit different: the `bin/openvscode-server` is still the same and for me it still exists in that location. Working just fine.

Sources to both of them:
- https://github.com/gitpod-io/openvscode-server/blob/main/resources/server/bin/code-server-linux.sh
- https://github.com/gitpod-io/openvscode-server/blob/main/resources/server/bin/remote-cli/code.sh

Are you facing any issue with the `bin/openvscode-server` script?

**Comment by ql-isaac** [comment]
@filiptronicek Thank you for your reply,my problem has been solved.I found out that [after v1.63.2 the way of running the server had changed](https://github.com/gitpod-io/openvscode-server/issues/300).
