### ISSUE TITLE
怎么支持中文界面？

### ISSUE THREAD

**Issue by zhouxiaoshan118** [gitpod-io/openvscode-server#338]
有知道的不？

**Comment by jeanp413** [comment]
Hi @zhouxiaoshan118, could you create the issue in english please :pray: . From using google translator It seems you are looking to change the display language currently that's not possible, related upstream issue https://github.com/microsoft/vscode/issues/82595

**Comment by huangyinhaow** [comment]
But vscode.dev support Chinese now.
