### ISSUE TITLE
implement tunnel connection

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/openvscode-server#34]

**Comment by asabi** [comment]
I'm not sure what you mean entirely, but I can do the following on my Mac:

```
ssh -N -f -L 3000:127.0.0.1:3000 ubuntu@ec2-my-ip.us-west-2.compute.amazonaws.com
```

That allows me to open my browser on localhost:3000 and use the browser VS code on my remote server.

**Comment by MikeSoft** [comment]
> I'm not sure what you mean entirely, but I can do the following on my Mac:
> 
> ```
> ssh -N -f -L 3000:127.0.0.1:3000 ubuntu@ec2-my-ip.us-west-2.compute.amazonaws.com
> ```
> 
> That allows me to open my browser on localhost:3000 and use the browser VS code on my remote server without exposing 3000 to the world.
> 
> I probably oversimplify things 😂

I love your command, do you know how to make it different?

Run in the external host a local port?

**Comment by akosyakov** [comment]
We switched to the upstream server, it already supports this connection.
