### ISSUE TITLE
The workbench failed to connect to the server (Error: Time limit reached)

### ISSUE THREAD

**Issue by 1250285855** [gitpod-io/openvscode-server#345]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.1 & 1.64.0
- OS Version: Ubuntu 20.0.04 LTS

Steps to Reproduce:

1. wget the release package
2.tar -xzf the package 
3.cd into the bin folder and run the server by command : ./openvscode-server --without-connection-token --host 0.0.0.0
4.and visit the server through my local computer : MacBook by Safari
5.then I will see the Error window like this 
<img width="1728" alt="截屏2022-04-24 04 31 32" src="https://user-images.githubusercontent.com/49292942/164945135-917408e8-deb3-4f17-959c-9f44b935e870.png">
6.if I click the "Reload", after few seconds, this window will appear again.

It's something wrong setting of my server? or something else?
Looking for help

**Comment by jeanp413** [comment]
Hi @1250285855, have you setup a reverse proxy on your server? are you accessing the workbench using `https` or `http`?

**Comment by 1250285855** [comment]
> Hi @1250285855, have you setup a reverse proxy on your server? are you accessing the workbench using `https` or `http`?

I think i don’t setup any reverse proxy on my server.
I try to accessing the workbench using http but looks like the server redirect to the ip without http agreement.

I use other computer to visit the workbench not going to happen this problem, and on my MacBook using Google Chrome the problem also not occur. so this problem seems to only happens on my MacBook Safari. Maybe something wrong with the user config on server.

**Comment by jeanp413** [comment]
If you are accessing the workbench using `http` then some features won't work like webviews and the web worker extension host as it requires a secure context i.e. `https` or `localhost` as an exception.
You can try this: doing an [ssh tunnel first](https://github.com/gitpod-io/openvscode-server/discussions/319#discussioncomment-2298644) and then accessing the workbench using `localhost`

**Comment by 1250285855** [comment]
> If you are accessing the workbench using http then some features won't work like webviews and the web worker extension host as it requires a secure context i.e. https or localhost as an exception.
> You can try this: doing an ssh tunnel first and then accessing the workbench using localhost

OK, Thank you.
