### ISSUE TITLE
Mac M1 and 32 bit support

### ISSUE THREAD

**Issue by bigint** [gitpod-io/openvscode-server#36]
It would be great if we have mac M1 and 32 bit support too 🙇🏻

**Comment by kolanski** [comment]
Hi, I interested in this feature too. May be we can discuss about our steps to make this true? I think we just need to recognize components, that require recompile to 32bit.

**Comment by andymac4182** [comment]
Curious what is the benefit of 32bit? Most hardware these days is 64bit.

**Comment by vimeh** [comment]
> Curious what is the benefit of 32bit? Most hardware these days is 64bit.

Most Raspberry Pi’s run a 32-bit version of Debian

**Comment by vimesh-shah** [comment]
Please add M1 and raspberry pi support.

**Comment by ayush--s** [comment]
can we have linux arm build please?

**Comment by anshuman852** [comment]
yes +1 on the arm build too

**Comment by neuronick** [comment]
+1

**Comment by MohamedElashri** [comment]
I tried to build for ARM using releases repo [Dockerfile](https://github.com/gitpod-io/openvscode-releases/blob/main/Dockerfile), but the problem is that open server itself doesn't support `arm` as there are many `amd64` dependencies.  I hope that you can address that.

**Comment by zdillon90** [comment]
+1 for a arm raspberry pi build

**Comment by Jazb** [comment]
+1 arm64 for Raspberry too.

**Comment by dictcp** [comment]
there is an alternative build (with ARM64 support) at
https://github.com/dictcp/docker-openvscode-server

You may use docker image `dictcp/openvscode-server` (or `ghcr.io/dictcp/openvscode-server`)

**Comment by MohamedElashri** [comment]
> there is an alternative build (with ARM64 support) at https://medium.com/@dictcp/self-hosting-your-vscode-online-ide-from-raspberry-pi-4-to-aws-graviton2-d2d351379340
> 
> You may use docker image `dictcp/openvscode-server` (or `ghcr.io/dictcp/openvscode-server`) as drop-in replacement of `gitpod/openvscode-server` for the time being

Thank you, this seems very helpful. would you mind share the `Dockerfile` if someone wants to build it

**Comment by dictcp** [comment]
> > there is an alternative build (with ARM64 support) at https://medium.com/@dictcp/self-hosting-your-vscode-online-ide-from-raspberry-pi-4-to-aws-graviton2-d2d351379340
> > You may use docker image `dictcp/openvscode-server` (or `ghcr.io/dictcp/openvscode-server`) as drop-in replacement of `gitpod/openvscode-server` for the time being
> 
> Thank you, this seems very helpful. would you mind share the `Dockerfile` if someone wants to build it

You may check at
https://github.com/dictcp/docker-openvscode-server/blob/master/Dockerfile

**Comment by Cyber1000** [comment]
@dictcp You are perfectly right, my mistake I tested this on different machines. Your script does exactly the same (you are using node:14 for building vscode-server, whereas here workspace-full is used, but that doesn't really matter)

@filiptronicek maybe your workspace-images also should be multiarch (I don't know your complete buildchain though), so far as I've seen workspace-base can be fully build on rpi4 (aka arm64), workspace-full would need some arm-specific-adjustments

**Comment by felipecrs** [comment]
I believe this is a requirement for switching to OpenVSCode Server on Home Assistant too:

https://github.com/hassio-addons/addon-vscode/issues/335

Most HA are installed in Raspberry Pis (ARM).

**Comment by akosyakov** [comment]
PRs are welcomed here: https://github.com/gitpod-io/vscode-releases

**Comment by eitsupi** [comment]
It looks like there are only amd64 builds in this repository release, can you build non-amd64 container images?

**Comment by felipecrs** [comment]
@eitsupi in the next release there should be ARM 32 and 64-bit

**Comment by eitsupi** [comment]
@felipecrs Is that possible at this time?
Need to be able to release non-amd64 builds to close this issue?

**Comment by felipecrs** [comment]
@eitsupi, let's wait for a word from the maintainers :)

**Comment by eitsupi** [comment]
Sorry, I understood that the artifacts attached to the release in this repository are built in another repository.
I hope that workflow works fine!

**Comment by felipecrs** [comment]
The new architectures are available in the 1.63 version of OpenVSCode Server Insiders, [as pointed by](https://github.com/gitpod-io/openvscode-releases/pull/14#issuecomment-966341907) @filiptronicek.

https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-insiders-v1.63.0
