### ISSUE TITLE
ipv6 spliting issue

### ISSUE THREAD

**Issue by wkr1423** [gitpod-io/openvscode-server#362]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.67.2
- OS Version: Ubuntu 21.10

Steps to Reproduce:
1.The server binds the ipv6 address
2.Access it with the ipv6 address

What causes the problem:
VSCode uses ":" to split the address, the content before ":" is the domain and the numbers afer the ":" is the port
but there are 7 ":" in the IPv6 address
![untitled](https://user-images.githubusercontent.com/57672685/172035876-e4b8ace0-2053-421a-8e4a-63b1ad574e41.png)
![2022-06-05 13-07-58 的屏幕截图](https://user-images.githubusercontent.com/57672685/172035939-438aa21c-2b3e-4d12-85a1-90753c10c492.png)

Solution:
use this to get address
`function getLocationByHref(rawLocation) {
  rawLocation = rawLocation.replace("http://", "").replace("https://", "");
  let pos = rawLocation.indexOf("/");
  let rightLocation = "";
  if (pos == -1) {
    pos = rawLocation.indexOf("?");
    if (pos == -1) {
      rightLocation = rawLocation;
      return rightLocation;
    }
  }
  for (let i = 0; i < pos; i++) {
    rightLocation += rawLocation[i];
  }
  return rightLocation;
}
`

**Comment by jeanp413** [comment]
@wkr1423 Thanks for reporting this, but as this issue is about core vscode, could your report it upstream https://github.com/microsoft/vscode/issues :pray: , you could even create a PR fixing it

**Comment by jeanp413** [comment]
Fixed by https://github.com/microsoft/vscode/pull/151500
