### ISSUE TITLE
url not escaped everywhere

### ISSUE THREAD

**Issue by jhgoebbert** [gitpod-io/openvscode-server#371]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Linux

Steps to Reproduce:
1. Open OpenVSCode behind an NGINX with a host-url which needs to be escaped like:  
    `https://jupyter-jsc.fz-juelich.de/my@email/hpcsystem/proxy/12345`. (example from a setup with JupyterHub+JupyterLab+jupyter-server-proxy)
2. The `@` inside the URL makes OpenVSCode stumble and fail.

I stumbled over this issue while testing the integration of OpenVSCode into JupyterLab here:  
https://github.com/FZJ-JSC/jupyter-openvscodeserver-proxy

This might look like a special issue but perhaps it helps in other situations, too.

**Comment by jeanp413** [comment]
Hi @jhgoebbert unfortunately upstream vscode does not support serving vscode from a path other than `/` yet (https://github.com/gitpod-io/openvscode-server/issues/320). 
There's been some work upstream to make this [easier to patch](https://github.com/gitpod-io/openvscode-server/issues/320#issuecomment-1120653022) but then you'll need to build from sources.

**Comment by jhgoebbert** [comment]
Great to hear that there are upcoming changes on that issue. I will check how much they can help with a setup build on top of [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy).  
Thank you for the links to more information!

**Comment by jhgoebbert** [comment]
I close this ticket as it might be more an issue of missing support of VSCode/OpenVSCode to run behind a configurable-http-proxy (like JupyterHub) than an issue on URL not escaped.
