### ISSUE TITLE
Pls. consider Dockerfile base image transition Ubuntu 20.04 to 22.04

### ISSUE THREAD

**Issue by wirepatch** [gitpod-io/openvscode-server#377]
Current Docker image https://github.com/gitpod-io/openvscode-releases is based on Ubuntu 20.04 shipping a Maven version being incompatible with Openjdk-17 (and others). This makes it difficult for Java folks to extend your image.

**Comment by jeanp413** [comment]
Thanks for bringing this up @wirepatch. 
@filiptronicek what do you think? I'd say let's update the base image to ubuntu 22.04, if users ask for 20.04 then we can look into adding more tags, something like `1.69.0-focal` and `1.69.0-jammy`

**Comment by filiptronicek** [comment]
@jeanp413 I think we should try it out and if everything builds correctly, I'll try testing it on my machine and if that is all good as well, we can merge the changes. I can take this.

I'm curious though @wirepatch about the incompatibility issue here: I'm not very familiar with Java, but I was able to install OpenJDK 17 with SDKMAN! just a couple of days ago.

**Comment by wirepatch** [comment]
BTW: Cheers for your excellent work. So far I'm just testing your beast but it really looks promising!

**Comment by filiptronicek** [comment]
Thanks @wirepatch for the kind words and the explanation 🧡!

and just to be clear here: are you reffering to the base image on https://gitpod.io or are you talking about OpenVSCode Server?

**Comment by wirepatch** [comment]
I do refer to your Docker image https://hub.docker.com/r/gitpod/openvscode-server. By virtue of https://github.com/gitpod-io/openvscode-releases/blob/main/Dockerfile this image starts from the Ubuntu 20.04 base image buildpack-deps:20.04-curl (my understanding so far at least). Your idea adding more tags sounds perfect.

BTW: The documentation at https://hub.docker.com/r/gitpod/openvscode-server uses `-v "$(pwd):/home/workspace:cached"`. Searching for the `cached` (sub)option a remark claimed this one having been obsoleted. It does not appear in the current reference documentation at https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container---volumes-from .

**Comment by filiptronicek** [comment]
> BTW: The documentation at [hub.docker.com/r/gitpod/openvscode-server](https://hub.docker.com/r/gitpod/openvscode-server) uses -v "$(pwd):/home/workspace:cached". Searching for the cached (sub)option a remark claimed this one having been obsoleted. It does not appear in the current reference documentation at [docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container---volumes-from](https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container---volumes-from) .

Thanks for noting, @wirepatch, I will revisit the docs we have here.
