### ISSUE TITLE
How can I compile openvscode-server so I don't have to have node installed

### ISSUE THREAD

**Issue by ubarilan** [gitpod-io/openvscode-server#413]
### Discussed in https://github.com/gitpod-io/openvscode-server/discussions/412

<div type='discussions-op-text'>

<sup>Originally posted by **ubarilan** August 16, 2022</sup>
Hello,
how can I compile this project into an executable so that I can use it without having to have NodeJS installed on the machine that openvscode-server is running on?</div>

**Comment by jeanp413** [comment]
closing this in favor of the linked discussion
