### ISSUE TITLE
Jupyter Notebook support broken after upgrading to 1.71.0

### ISSUE THREAD

**Issue by nappy** [gitpod-io/openvscode-server#426]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.71.0
- OS Version: Ubuntu 22.04.1 LTS
- Jupyter Extension Version: v2022.8.1002460559

Steps to Reproduce:

1. Install latest https://open-vsx.org/extension/ms-toolsai/jupyter Extension (v2022.8.1002460559) with latest openvscode-server docker release (1.71.0)
2. Press Ctrl Shift P and verify that Create: New Jupyter Notebook command is not present
3. Try open a file with .ipynb extension will yield the following error dialog : Unable to open 'notebook.ipynb' Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed and enabled.

I was upgrading from 1.66.1 to 1.71.0 because https://github.com/microsoft/vscode/issues/153892 was blocking me from upgrading earlier. In 1.66.1 Jupyter Notebooks worked flawlessly.

**Comment by mustard-mh** [comment]
I tried with [Gitpod](https://www.gitpod.io/) by steps below

- Open an empty workspace https://gitpod.new
- Exec `docker run -it --init -p 3000:3000 gitpod/openvscode-server` to start latest openvscode-server in docker
- Open it in browser by exec `gp preview $(gp url 3000) --external`
- Install the latest jupyter
- Find *new jupyter notebook* in all commands
- Create a new jupyter file, and "hello world" here (after all requirments installed)

It works well for me

|Version|Command|HelloWorld|
|-|-|-|
|<img width="1624" alt="image" src="https://user-images.githubusercontent.com/20944364/188564282-1bd4cb36-6108-4116-9b66-82b5864f396a.png">|<img width="1624" alt="image" src="https://user-images.githubusercontent.com/20944364/188563318-d297f547-d1e6-4da3-b778-a13420ed4f78.png">|<img width="1624" alt="image" src="https://user-images.githubusercontent.com/20944364/188563788-891a3aca-82cf-4167-b1e9-bc9bb1f8a3a5.png">|

Am I missing something? Could someone try it with docker without Gitpod? (I'm using M1 MacBook)

cc @jeanp413 @filiptronicek

**Comment by jeanp413** [comment]
Ah probably is the [issue with builtin extensions](https://github.com/gitpod-io/openvscode-server/discussions/418#discussioncomment-3443494), go to `/home/workspace/.openvscode-server/extensions` and remove all folders with this pattern `vscode.*-1.62.3`

**Comment by nappy** [comment]
Yes this was the issue. Thanks. Since I am using this on production I am persisting the home directory. Sorry for the incomplete reproduce steps.

**Comment by jeanp413** [comment]
yeah this issue is really annoying but if you are using the stable images it won't happen again, only insiders is affected
