### ISSUE TITLE
request for Dev Container extension

### ISSUE THREAD

**Issue by cjbd** [gitpod-io/openvscode-server#445]
done searching

Hello, I found the [Dev Container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension very useful, it's available in vscode, but not available in openvscode-server

vscode
![image](https://user-images.githubusercontent.com/49832282/196838278-91b106ee-8709-44c8-a571-a65649fd8a95.png)

openvscode server
![image](https://user-images.githubusercontent.com/49832282/196838318-2de4a115-32f8-4bc3-87a7-a79a4ed75f53.png)

If we run openvscode-server from linux environment, it should work like vscode, right? how come it's not in extension list? can you please add this extension for openvscode-server, thanks!

**Comment by Siddhant-K-code** [comment]
It is a proprietary VS Code Extension by Microsoft. And, Microsoft only allows the use of their marketplace for Microsoft Software (See the [MS ToS](https://cdn.vsassets.io/v/M190_20210811.1/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf) section 1f).

But, **you can use all of them on Gitpod** [**VS Code Desktop**](https://www.gitpod.io/docs/references/ides-and-editors/vscode). 

Hope it helps 🙏🏼
