### ISSUE TITLE
[Bug] Extension's status always is `installing` before reload the page

### ISSUE THREAD

**Issue by zWingz** [gitpod-io/openvscode-server#451]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.3

Steps to Reproduce:

1. install `spring boot dashboard` extension
2. search the extension by `@install` 
3. reload the page after 30s or more ?
4. the extension's status change to `installed`
5. uninstall the extension
6. install `spring boot dashboard` again

When install `Spring boot dashboard`, It will install the dependencies.
But I have installed all the dependencies, It still in `installing` status.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/13031838/197445647-816aa937-5720-4e13-8cbe-a89af71c84ca.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/13031838/197445631-4e171bc8-dcf2-44c8-a3a9-c7f06668427a.png">

After reload the page, it change to `installed`

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13031838/197445699-04f6e903-2d76-4d80-9970-ec845f4e3710.png">

If uninstall the `spring boot dashboard` extension, It can't be installed again
<img width="355" alt="image" src="https://user-images.githubusercontent.com/13031838/197447198-a1009294-bfbb-480c-9f44-c2dbbfb3fd4a.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/13031838/197447213-2e6cd7c5-0634-4cbf-8082-05970f0ff914.png">

**Comment by jeanp413** [comment]
@zWingz can you still reproduce, maybe it was related to open-vsx being down at that time.

**Comment by zWingz** [comment]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/13031838/199865572-b23bd7fd-aca2-4a5e-81c9-f13c0b6e3f8f.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/13031838/199865594-d9a317ae-fa8d-4cc6-adff-a934dceee6d8.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/13031838/199865615-c06c94c2-3625-4c4c-a9b0-8ba7aa6bc1ed.png">

@jeanp413

**Comment by jeanp413** [comment]
@zWingz I can reproduce it :+1: , created an issue upstream and a PR fixing it https://github.com/microsoft/vscode/issues/166196
