### ISSUE TITLE
Cannot use window object and some javascript api. I'm not sure whether it's my wrong usage or something

### ISSUE THREAD

**Issue by wzxinchen** [gitpod-io/openvscode-server#482]
I am developing an extension that works well before calling the window object.

When I call window, it reports this error

Activating extension 'wzxinchen.codegame' failed: window is not defined

My understanding is that because most of the code of openvscode runs on the server, including the code of extension there is no window object?

What should I do if I need my extension to run some code on the browser side?

**Comment by axonasif** [comment]
Hi @wzxinchen, could you try on [vscode-desktop](https://www.gitpod.io/docs/references/ides-and-editors/vscode) ?

**Comment by andreafalzetti** [comment]
cc @jeanp413

**Comment by jeanp413** [comment]
@wzxinchen you cannot use the window object in vscode extensions, If you are you using the webview api to render some content inside an iframe then you can use the window object there.
