### ISSUE TITLE
Ability to remove the Gitpod help menu options

### ISSUE THREAD

**Issue by dlvhdr** [gitpod-io/openvscode-server#491]
We are using the openvscode-server release from https://github.com/gitpod-io/openvscode-server/releases/

This comes with a customized help menu that we'd like to remove.

![image](https://user-images.githubusercontent.com/6196971/216319029-801adcd0-3799-42f0-a3c1-ebd80263d620.png)

Some of these options are not relevant to our VSCode product.
Is there an option to remove these?

**Comment by jeanp413** [comment]
You mean the `Join us on twitter`, `Search Feature`, `Report issue`? If so you can configure/delete them in the product.json file  https://github.com/gitpod-io/openvscode-server/blob/67f0395f2825114a4d79ae88cf286d7ea5313fb9/product.json#L29-L36

**Comment by dlvhdr** [comment]
Thank you!
