### ISSUE TITLE
Refused to create a worker because it violates the following Content Security Policy directive: "worker-src 'self' data:".

### ISSUE THREAD

**Issue by cjbd** [gitpod-io/openvscode-server#494]
Refused to create a worker because it violates the following Content Security Policy directive: "worker-src 'self' data:".

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Embedder: openvscode-server

I've been using openvscode-server for a while, this error message occurs since 1.75.0, there was no such error before
snapshot:
![3ff81a05f550a260143a6d87a5c6c4c](https://user-images.githubusercontent.com/49832282/219252938-237a7390-1d57-4491-8763-b6cd3478bb48.png)

however, even with this error in browser console, it seems most of the functions are still working, btw, i deployed openvscode-server behide nginx proxy with ssl

**Comment by jeanp413** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/173104, already fixed in insiders
