### ISSUE TITLE
Deploy server to Vercel

### ISSUE THREAD

**Issue by guylepage3** [gitpod-io/openvscode-server#502]
It would be very nice to be able to deploy to [Vercel](https://vercel.com). Anything in the work?

**Comment by filiptronicek** [comment]
Hello @guylepage3, the OpenVSCode Server project is meant to be run by a fully-fledged long-running server in the background, leveraging WebSockets to access the server with your code, terminals etc.

If you're looking into ways to run VS Code without a dedicated server, feel free to look at solutions such as https://github.com/conwnet/github1s.
