### ISSUE TITLE
Are extensions missing??? Cannot find remote-ssh extension

### ISSUE THREAD

**Issue by risharde** [gitpod-io/openvscode-server#526]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: openvscode-server-v1.81.0
- OS Version: Ubuntu 20

Steps to Reproduce:

1. Go to extensions, search remote-ssh or just remote ssh, you will see it doesn't find the Microsoft Remote SSH extension. Making this unusable for me.
![image](https://github.com/gitpod-io/openvscode-server/assets/33866403/08eb125b-f83e-4e41-b471-aad4a92a13b9)

**Comment by jeanp413** [comment]
Hi @risharde 
Microsoft Remote SSH extension is only available in the official MS marketplace, openvscode-server uses https://open-vsx.org/ as the marketplace, also it's not possible to use the Microsoft Remote SSH extension with vscode running in the browser it's only meant to be used with vscode desktop

**Comment by lokize** [comment]
its possible to install ms marketplace extensions manually?
