### ISSUE TITLE
Missing release for insiders 1.82

### ISSUE THREAD

**Issue by aptalca** [gitpod-io/openvscode-server#528]
Does this issue occur when all extensions are disabled?: 
N/A

- VS Code Version: 1.82
- OS Version: 

Steps to Reproduce:

1. 
2. 

There is a GitHub tag for insiders version 1.82 but no release. In fact there are no insiders releases listed there. I believe the ci deletes the older insiders release before pushing a new release. In this case it seems it deleted the old one but failed to push the new one.

Out of curiosity, what is the purpose of deleting the older insiders releases? They are already marked as `prerelease` so they wouldn't be confused with the stable releases even if the versions were the same.

Thanks

**Comment by jeanp413** [comment]
Fixed :pray: 

> what is the purpose of deleting the older insiders releases? 

Insiders are generated daily and more often than not are buggy, it's just used to generate the insiders docker image which is also updated daily
