### ISSUE TITLE
[gitpod extension] - Add a Welcome screen walkthrough

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/openvscode-server#53]
As a person who is unfamiliar with Gitpod, but happens to open a Gitpod workspace (e.g. by clicking an "Open in Gitpod" button on a repo),
I want an opportunity to have an in-workspace "Get Started with Gitpod" experience
so that I can familiarize myself with Gitpod, its features and benefits.

**Comment by JohannesLandgraf** [comment]
Is this the right place for Gitpod specific PRs @akosyakov?

**Comment by akosyakov** [comment]
I think for gitpod we shoudl use gitpod-io, and keep this one for openvscode issues.

**Comment by mikenikles** [comment]
👍 I'll move it. I opened it here because the code is in this repo's `gp-code` branch but agreed, let's keep Gitpod issues in the other repo.
