### ISSUE TITLE
FIeld ID's not updating in Wix IDE 

### ISSUE THREAD

**Issue by DanielBrightSpark** [gitpod-io/openvscode-server#551]
Hey Wix team. 

I've updated the ID's of my fields to be relevant to the content they collect. However, the new ID's are not being recognised as Valid.

My email is Daniel@brightsparksagency.com if you would care to help/

Kind regards

Dan

Version: 1.79.2
Commit: 6c3eb9ae5f4d44be88307d2137e8364e0e36891a
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: openvscode-server

**Comment by filiptronicek** [comment]
Hi @DanielBrightSpark, we are the Gitpod team, not Wix. I assume you stumbled upon a fork of the project, which Wix maintains, and which has not updated the bug reporting URLs to point to a repo of theirs. Could you please instead raise your issue somewhere where Wix folks can find it?

**Comment by DanielBrightSpark** [comment]
Ah I see, thanks for the clarification
