### ISSUE TITLE
[Guides] Create Guide For Azure VM

### ISSUE THREAD

**Issue by hrittikhere** [gitpod-io/openvscode-server#77]
Hey, Would you be comfortable if I create a quick guide for running the Instance on Azure VMs? I do work with Azure a lot and maybe it would help people. Please let me know! Thanks.

**Comment by mikenikles** [comment]
Hey 👋, yes absolutely! It's all yours. I wrote a few thoughts on how to add a new guide, trying to keep them as similar as possible in terms of the structure. See https://github.com/gitpod-io/openvscode-server/tree/main/docs/guides#add-a-new-guide.

Please tag me in the PR once it's ready and I'll help get it merged.

**Comment by hrittikhere** [comment]
Sure, Thanks! Can you please assign me the issue?
