### ISSUE TITLE
Username and group is “vscode-server” not “openvscode-server”

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/openvscode-server#86]
In :latest we are using the old name as the username that executes the process/owner of files.

https://github.com/gitpod-io/openvscode-releases/blob/5ce0281a5d15b4d8575062ff0732334202a5ec80/Dockerfile#L17

**Comment by mikenikles** [comment]
Please also update the user in the `README.md`, introduced via https://github.com/gitpod-io/openvscode-server/pull/102/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R41

**Comment by jeanp413** [comment]
Fixed this in https://github.com/gitpod-io/openvscode-releases/commit/018a2459d40eba91a82eeddb3c1510a9d3c79d0f
Also updated the readme file
