### ISSUE TITLE
sudo is not installed

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/openvscode-server#87]
I’m using :latest

We should make it easier for people to mutate the docker image/install software when the server is running.

**Comment by ghuntley** [comment]
```code
# Configure sudo
RUN apt-get update \ 
    && apt-get install -y sudo \
    && adduser vscode-server sudo \
    && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
```

Nb: change vscode-server when #86 is resolved.

**Comment by jeanp413** [comment]
Fixed this in https://github.com/gitpod-io/openvscode-releases/commit/018a2459d40eba91a82eeddb3c1510a9d3c79d0f

**Comment by MohamedElashri** [comment]
I think the official image still need to be built to accompany that fix

**Comment by jeanp413** [comment]
@MohamedElashri Docker images are updated with the fix
