### ISSUE TITLE
Add ability to host on subdirectory

### ISSUE THREAD

**Issue by WizzardMaker** [gitpod-io/openvscode-server#90]
I would like to be able to host VS Code on a subdir on my domain (e.g. my-domain.com/vscode/), but a lot of scripts and the websocket connections default to the subdir-less host and often drop the correct referer, making it hard to serve VSCode on a subdirectory with nginx.

**Comment by Livven** [comment]
We are in the process of migrating from code-server and also ran into this issue. We've gotten it mostly running now, only things missing are service worker calls and syntax highlighting as far as I can tell. Will open a PR once we have it in a decent state, which should be later this week or early next week.

**Comment by akosyakov** [comment]
Just to clarify we are not going to accept changes to the server, since it was open-sourced by MS: https://www.gitpod.io/blog/vscode-server It would be the best if you open a PR in the upstream: https://github.com/microsoft/vscode

**Comment by akosyakov** [comment]
I'm going to close it for now. I think it is the upstream issue.

**Comment by fritterhoff** [comment]
> 
> 
> We are in the process of migrating from code-server and also ran into this issue. We've gotten it mostly running now, only things missing are service worker calls and syntax highlighting as far as I can tell. Will open a PR once we have it in a decent state, which should be later this week or early next week.

Would be great if you manage to get it working inside a subfolder. I'm also very interested in hosting the server in an other path than root 😀 .
