### ISSUE TITLE
Broken/missing terminal locale setting in docker image

### ISSUE THREAD

**Issue by flxs** [gitpod-io/openvscode-server#92]
Typing UTF-8 characters like `äöüß` into the terminal doesn't work properly, they seem to be misinterpreted as control codes, which in the case of `ö` on a German keyboard messes up the whole current line. Tested using the latest Docker image in the web UI terminal (fully updated Firefox on macOS Big Sur and Safari on iPad) and in a `docker exec`-ed `bash`.

I noticed that the locale-specific environment variables either aren't set (`docker exec`) or are set to `LANG=en_US.UTF-8`, which isn't present in the image, only `C`, `C.UTF-8` and `POSIX`. Setting the locale to `C.UTF-8` by passing `-e LANG=C.UTF-8 -e LC_ALL=C.UTF-8` to the `docker run` invocation makes it work for me (so setting these in the Dockerfile should fix this.)

**Comment by jeanp413** [comment]
Fixed by https://github.com/gitpod-io/openvscode-releases/pull/10 . Will update the docker images tomorrow.
