### ISSUE TITLE
Error Previewing Extensions - Service Workers are not enabled. Webviews will not work. (macOS)

### ISSUE THREAD

**Issue by calebcoverdale** [gitpod-io/openvscode-server#93]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.60.2 | v1.61.0
- OS Version: Ubuntu | Docker
- Client OS: macOS

Steps to Reproduce:
I start either the docker container, or run the OpenVSCode-Server from the folder and I get an error saying "Error: Service workers are not enabled. Webviews will not work. Try disabling private/incognito mode. 

1. I have tried Edge on macOS as well as Safari and the issue persists. 
2. I cleared the cache on client browsers
3. Rebooted the host machine 

Any thoughts would be helpful! 

Love the project.

**Comment by jeanp413** [comment]
@calebcoverdale if you are testing it just locally `http://localhost:3000` should also work.
